########################################################################
 # Copyright (c) Intel Corporation 2023
########################################################################

version: '3.7'

services:
  app-sample-service:
    container_name: app-sample-service
    depends_on:
      consul:
        condition: service_started
    env_file:
      .env
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: app-sample-service
      SOUNDS: "Gunshot,Door knock"
    hostname: app-sample-service
    image: hackathon/app-sample-service:dev
    networks:
      edgex-network: {}
    ports:
      - 127.0.0.1:59741:59741/tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001