site_name: Team Jedi Hackathon - Remote Sensing Solutions
docs_dir: ./docs_src
site_dir: ./docs
copyright: 'Copyright &copy; 2023 Intel Corporation'
use_directory_urls: false
theme:
  name: 'material'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/logo-white-75px.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - navigation.top
    - toc.integrate
  icon:
    repo: fontawesome/brands/git-alt
repo_url: https://github.com/NeethuES-intel/team-jedi-hackathon-dev
repo_name: intel/team-jedi-hackathon-dev 
plugins:
  - search
  - swagger-ui-tag:
      syntaxHighlightTheme: monokai
      supportedSubmitMethods: []
      validatorUrl: none
nav:
  - Home:
    - Overview: index.md
extra_javascript:
  - 'https://unpkg.com/lunr/lunr.js'
# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - pymdownx.snippets
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
extra_css:
  - ./stylesheets/index.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - ./stylesheets/branding.css
  - ./stylesheets/extra.css
